# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('notes', '0002_notes_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='folders.Folder'),
        ),
    ]
