# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='notes',
            name='text',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
