# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 10:30
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180526_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='contents',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
