# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notes_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='text',
        ),
    ]
